function test_quantity_options()
%TEST_QUANTITY_OPTIONS Verify name-value options for scalar and vector quantities.
    scriptDir = fileparts(mfilename('fullpath'));
    rootDir = fileparts(scriptDir);
    addpath(fullfile(rootDir, 'src', 'matlab'));

    ps = polyscope.Polyscope;
    ps.init('openGL_mock');
    ps.remove_everything();

    pts = randn(10, 3);
    pc = ps.register_point_cloud('cloud', pts);

    pc.add_scalar_quantity('s1', randn(10, 1), ...
        'datatype', 'symmetric', ...
        'map_range', [-1, 1], ...
        'color_map', 'viridis', ...
        'onscreen_colorbar_enabled', true, ...
        'isolines_enabled', true, ...
        'isoline_style', 'stripe', ...
        'isoline_period', 0.5);

    pc.add_vector_quantity('v1', randn(10, 3), ...
        'vectortype', 'ambient', ...
        'length', 0.2, ...
        'length_relative', false, ...
        'radius', 0.01, ...
        'color', [1, 0, 0], ...
        'material', 'wax');

    ps.frame_tick();
    ps.shutdown();
    fprintf('test_quantity_options passed\n');
end
