// AUTO-GENERATED implot constant lookup
#include "command_router.h"
#include "matlab_data_utils.h"
#include "implot.h"

namespace ps_mex {

void bind_implot_constant_lookup(CommandRegistry& reg) {
  reg.registerCommand("implot_get_constant", [](matlab::mex::ArgumentList& outputs,
                                                   matlab::mex::ArgumentList& inputs,
                                                   matlab::engine::MATLABEngine* matlabPtr) {
    if (inputCount(inputs) < 2) throwError(matlabPtr, "Expected {lib}_get_constant(name)");
    std::string name = getString(getInput(inputs, 1));
    matlab::data::ArrayFactory factory;
    if (name == "ImAxis_X1") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImAxis_X1)); return; }
    if (name == "ImAxis_X2") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImAxis_X2)); return; }
    if (name == "ImAxis_X3") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImAxis_X3)); return; }
    if (name == "ImAxis_Y1") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImAxis_Y1)); return; }
    if (name == "ImAxis_Y2") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImAxis_Y2)); return; }
    if (name == "ImAxis_Y3") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImAxis_Y3)); return; }
    if (name == "ImAxis_COUNT") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImAxis_COUNT)); return; }
    if (name == "IMPLOT_AUTO") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(IMPLOT_AUTO)); return; }
    if (name == "ImPlotFlags_None") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotFlags_None)); return; }
    if (name == "ImPlotFlags_NoTitle") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotFlags_NoTitle)); return; }
    if (name == "ImPlotFlags_NoLegend") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotFlags_NoLegend)); return; }
    if (name == "ImPlotFlags_NoMouseText") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotFlags_NoMouseText)); return; }
    if (name == "ImPlotFlags_NoInputs") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotFlags_NoInputs)); return; }
    if (name == "ImPlotFlags_NoMenus") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotFlags_NoMenus)); return; }
    if (name == "ImPlotFlags_NoBoxSelect") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotFlags_NoBoxSelect)); return; }
    if (name == "ImPlotFlags_NoFrame") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotFlags_NoFrame)); return; }
    if (name == "ImPlotFlags_Equal") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotFlags_Equal)); return; }
    if (name == "ImPlotFlags_Crosshairs") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotFlags_Crosshairs)); return; }
    if (name == "ImPlotFlags_CanvasOnly") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotFlags_CanvasOnly)); return; }
    if (name == "ImPlotAxisFlags_None") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotAxisFlags_None)); return; }
    if (name == "ImPlotAxisFlags_NoLabel") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotAxisFlags_NoLabel)); return; }
    if (name == "ImPlotAxisFlags_NoGridLines") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotAxisFlags_NoGridLines)); return; }
    if (name == "ImPlotAxisFlags_NoTickMarks") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotAxisFlags_NoTickMarks)); return; }
    if (name == "ImPlotAxisFlags_NoTickLabels") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotAxisFlags_NoTickLabels)); return; }
    if (name == "ImPlotAxisFlags_NoInitialFit") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotAxisFlags_NoInitialFit)); return; }
    if (name == "ImPlotAxisFlags_NoMenus") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotAxisFlags_NoMenus)); return; }
    if (name == "ImPlotAxisFlags_NoSideSwitch") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotAxisFlags_NoSideSwitch)); return; }
    if (name == "ImPlotAxisFlags_NoHighlight") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotAxisFlags_NoHighlight)); return; }
    if (name == "ImPlotAxisFlags_Opposite") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotAxisFlags_Opposite)); return; }
    if (name == "ImPlotAxisFlags_Foreground") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotAxisFlags_Foreground)); return; }
    if (name == "ImPlotAxisFlags_Invert") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotAxisFlags_Invert)); return; }
    if (name == "ImPlotAxisFlags_AutoFit") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotAxisFlags_AutoFit)); return; }
    if (name == "ImPlotAxisFlags_RangeFit") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotAxisFlags_RangeFit)); return; }
    if (name == "ImPlotAxisFlags_PanStretch") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotAxisFlags_PanStretch)); return; }
    if (name == "ImPlotAxisFlags_LockMin") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotAxisFlags_LockMin)); return; }
    if (name == "ImPlotAxisFlags_LockMax") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotAxisFlags_LockMax)); return; }
    if (name == "ImPlotAxisFlags_Lock") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotAxisFlags_Lock)); return; }
    if (name == "ImPlotAxisFlags_NoDecorations") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotAxisFlags_NoDecorations)); return; }
    if (name == "ImPlotAxisFlags_AuxDefault") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotAxisFlags_AuxDefault)); return; }
    if (name == "ImPlotSubplotFlags_None") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotSubplotFlags_None)); return; }
    if (name == "ImPlotSubplotFlags_NoTitle") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotSubplotFlags_NoTitle)); return; }
    if (name == "ImPlotSubplotFlags_NoLegend") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotSubplotFlags_NoLegend)); return; }
    if (name == "ImPlotSubplotFlags_NoMenus") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotSubplotFlags_NoMenus)); return; }
    if (name == "ImPlotSubplotFlags_NoResize") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotSubplotFlags_NoResize)); return; }
    if (name == "ImPlotSubplotFlags_NoAlign") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotSubplotFlags_NoAlign)); return; }
    if (name == "ImPlotSubplotFlags_ShareItems") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotSubplotFlags_ShareItems)); return; }
    if (name == "ImPlotSubplotFlags_LinkRows") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotSubplotFlags_LinkRows)); return; }
    if (name == "ImPlotSubplotFlags_LinkCols") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotSubplotFlags_LinkCols)); return; }
    if (name == "ImPlotSubplotFlags_LinkAllX") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotSubplotFlags_LinkAllX)); return; }
    if (name == "ImPlotSubplotFlags_LinkAllY") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotSubplotFlags_LinkAllY)); return; }
    if (name == "ImPlotSubplotFlags_ColMajor") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotSubplotFlags_ColMajor)); return; }
    if (name == "ImPlotLegendFlags_None") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotLegendFlags_None)); return; }
    if (name == "ImPlotLegendFlags_NoButtons") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotLegendFlags_NoButtons)); return; }
    if (name == "ImPlotLegendFlags_NoHighlightItem") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotLegendFlags_NoHighlightItem)); return; }
    if (name == "ImPlotLegendFlags_NoHighlightAxis") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotLegendFlags_NoHighlightAxis)); return; }
    if (name == "ImPlotLegendFlags_NoMenus") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotLegendFlags_NoMenus)); return; }
    if (name == "ImPlotLegendFlags_Outside") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotLegendFlags_Outside)); return; }
    if (name == "ImPlotLegendFlags_Horizontal") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotLegendFlags_Horizontal)); return; }
    if (name == "ImPlotLegendFlags_Sort") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotLegendFlags_Sort)); return; }
    if (name == "ImPlotMouseTextFlags_None") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotMouseTextFlags_None)); return; }
    if (name == "ImPlotMouseTextFlags_NoAuxAxes") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotMouseTextFlags_NoAuxAxes)); return; }
    if (name == "ImPlotMouseTextFlags_NoFormat") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotMouseTextFlags_NoFormat)); return; }
    if (name == "ImPlotMouseTextFlags_ShowAlways") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotMouseTextFlags_ShowAlways)); return; }
    if (name == "ImPlotDragToolFlags_None") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotDragToolFlags_None)); return; }
    if (name == "ImPlotDragToolFlags_NoCursors") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotDragToolFlags_NoCursors)); return; }
    if (name == "ImPlotDragToolFlags_NoFit") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotDragToolFlags_NoFit)); return; }
    if (name == "ImPlotDragToolFlags_NoInputs") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotDragToolFlags_NoInputs)); return; }
    if (name == "ImPlotDragToolFlags_Delayed") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotDragToolFlags_Delayed)); return; }
    if (name == "ImPlotColormapScaleFlags_None") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotColormapScaleFlags_None)); return; }
    if (name == "ImPlotColormapScaleFlags_NoLabel") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotColormapScaleFlags_NoLabel)); return; }
    if (name == "ImPlotColormapScaleFlags_Opposite") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotColormapScaleFlags_Opposite)); return; }
    if (name == "ImPlotColormapScaleFlags_Invert") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotColormapScaleFlags_Invert)); return; }
    if (name == "ImPlotItemFlags_None") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotItemFlags_None)); return; }
    if (name == "ImPlotItemFlags_NoLegend") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotItemFlags_NoLegend)); return; }
    if (name == "ImPlotItemFlags_NoFit") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotItemFlags_NoFit)); return; }
    if (name == "ImPlotLineFlags_None") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotLineFlags_None)); return; }
    if (name == "ImPlotLineFlags_Segments") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotLineFlags_Segments)); return; }
    if (name == "ImPlotLineFlags_Loop") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotLineFlags_Loop)); return; }
    if (name == "ImPlotLineFlags_SkipNaN") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotLineFlags_SkipNaN)); return; }
    if (name == "ImPlotLineFlags_NoClip") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotLineFlags_NoClip)); return; }
    if (name == "ImPlotLineFlags_Shaded") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotLineFlags_Shaded)); return; }
    if (name == "ImPlotScatterFlags_None") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotScatterFlags_None)); return; }
    if (name == "ImPlotScatterFlags_NoClip") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotScatterFlags_NoClip)); return; }
    if (name == "ImPlotStairsFlags_None") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotStairsFlags_None)); return; }
    if (name == "ImPlotStairsFlags_PreStep") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotStairsFlags_PreStep)); return; }
    if (name == "ImPlotStairsFlags_Shaded") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotStairsFlags_Shaded)); return; }
    if (name == "ImPlotShadedFlags_None") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotShadedFlags_None)); return; }
    if (name == "ImPlotBarsFlags_None") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotBarsFlags_None)); return; }
    if (name == "ImPlotBarsFlags_Horizontal") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotBarsFlags_Horizontal)); return; }
    if (name == "ImPlotBarGroupsFlags_None") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotBarGroupsFlags_None)); return; }
    if (name == "ImPlotBarGroupsFlags_Horizontal") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotBarGroupsFlags_Horizontal)); return; }
    if (name == "ImPlotBarGroupsFlags_Stacked") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotBarGroupsFlags_Stacked)); return; }
    if (name == "ImPlotErrorBarsFlags_None") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotErrorBarsFlags_None)); return; }
    if (name == "ImPlotErrorBarsFlags_Horizontal") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotErrorBarsFlags_Horizontal)); return; }
    if (name == "ImPlotStemsFlags_None") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotStemsFlags_None)); return; }
    if (name == "ImPlotStemsFlags_Horizontal") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotStemsFlags_Horizontal)); return; }
    if (name == "ImPlotInfLinesFlags_None") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotInfLinesFlags_None)); return; }
    if (name == "ImPlotInfLinesFlags_Horizontal") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotInfLinesFlags_Horizontal)); return; }
    if (name == "ImPlotPieChartFlags_None") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotPieChartFlags_None)); return; }
    if (name == "ImPlotPieChartFlags_Normalize") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotPieChartFlags_Normalize)); return; }
    if (name == "ImPlotPieChartFlags_IgnoreHidden") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotPieChartFlags_IgnoreHidden)); return; }
    if (name == "ImPlotPieChartFlags_Exploding") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotPieChartFlags_Exploding)); return; }
    if (name == "ImPlotHeatmapFlags_None") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotHeatmapFlags_None)); return; }
    if (name == "ImPlotHeatmapFlags_ColMajor") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotHeatmapFlags_ColMajor)); return; }
    if (name == "ImPlotHistogramFlags_None") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotHistogramFlags_None)); return; }
    if (name == "ImPlotHistogramFlags_Horizontal") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotHistogramFlags_Horizontal)); return; }
    if (name == "ImPlotHistogramFlags_Cumulative") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotHistogramFlags_Cumulative)); return; }
    if (name == "ImPlotHistogramFlags_Density") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotHistogramFlags_Density)); return; }
    if (name == "ImPlotHistogramFlags_NoOutliers") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotHistogramFlags_NoOutliers)); return; }
    if (name == "ImPlotHistogramFlags_ColMajor") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotHistogramFlags_ColMajor)); return; }
    if (name == "ImPlotDigitalFlags_None") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotDigitalFlags_None)); return; }
    if (name == "ImPlotImageFlags_None") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotImageFlags_None)); return; }
    if (name == "ImPlotTextFlags_None") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotTextFlags_None)); return; }
    if (name == "ImPlotTextFlags_Vertical") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotTextFlags_Vertical)); return; }
    if (name == "ImPlotDummyFlags_None") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotDummyFlags_None)); return; }
    if (name == "ImPlotCond_None") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotCond_None)); return; }
    if (name == "ImPlotCond_Always") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotCond_Always)); return; }
    if (name == "ImPlotCond_Once") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotCond_Once)); return; }
    if (name == "ImPlotCol_Line") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotCol_Line)); return; }
    if (name == "ImPlotCol_Fill") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotCol_Fill)); return; }
    if (name == "ImPlotCol_MarkerOutline") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotCol_MarkerOutline)); return; }
    if (name == "ImPlotCol_MarkerFill") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotCol_MarkerFill)); return; }
    if (name == "ImPlotCol_ErrorBar") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotCol_ErrorBar)); return; }
    if (name == "ImPlotCol_FrameBg") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotCol_FrameBg)); return; }
    if (name == "ImPlotCol_PlotBg") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotCol_PlotBg)); return; }
    if (name == "ImPlotCol_PlotBorder") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotCol_PlotBorder)); return; }
    if (name == "ImPlotCol_LegendBg") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotCol_LegendBg)); return; }
    if (name == "ImPlotCol_LegendBorder") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotCol_LegendBorder)); return; }
    if (name == "ImPlotCol_LegendText") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotCol_LegendText)); return; }
    if (name == "ImPlotCol_TitleText") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotCol_TitleText)); return; }
    if (name == "ImPlotCol_InlayText") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotCol_InlayText)); return; }
    if (name == "ImPlotCol_AxisText") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotCol_AxisText)); return; }
    if (name == "ImPlotCol_AxisGrid") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotCol_AxisGrid)); return; }
    if (name == "ImPlotCol_AxisTick") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotCol_AxisTick)); return; }
    if (name == "ImPlotCol_AxisBg") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotCol_AxisBg)); return; }
    if (name == "ImPlotCol_AxisBgHovered") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotCol_AxisBgHovered)); return; }
    if (name == "ImPlotCol_AxisBgActive") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotCol_AxisBgActive)); return; }
    if (name == "ImPlotCol_Selection") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotCol_Selection)); return; }
    if (name == "ImPlotCol_Crosshairs") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotCol_Crosshairs)); return; }
    if (name == "ImPlotCol_COUNT") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotCol_COUNT)); return; }
    if (name == "ImPlotStyleVar_LineWeight") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotStyleVar_LineWeight)); return; }
    if (name == "ImPlotStyleVar_Marker") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotStyleVar_Marker)); return; }
    if (name == "ImPlotStyleVar_MarkerSize") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotStyleVar_MarkerSize)); return; }
    if (name == "ImPlotStyleVar_MarkerWeight") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotStyleVar_MarkerWeight)); return; }
    if (name == "ImPlotStyleVar_FillAlpha") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotStyleVar_FillAlpha)); return; }
    if (name == "ImPlotStyleVar_ErrorBarSize") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotStyleVar_ErrorBarSize)); return; }
    if (name == "ImPlotStyleVar_ErrorBarWeight") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotStyleVar_ErrorBarWeight)); return; }
    if (name == "ImPlotStyleVar_DigitalBitHeight") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotStyleVar_DigitalBitHeight)); return; }
    if (name == "ImPlotStyleVar_DigitalBitGap") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotStyleVar_DigitalBitGap)); return; }
    if (name == "ImPlotStyleVar_PlotBorderSize") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotStyleVar_PlotBorderSize)); return; }
    if (name == "ImPlotStyleVar_MinorAlpha") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotStyleVar_MinorAlpha)); return; }
    if (name == "ImPlotStyleVar_MajorTickLen") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotStyleVar_MajorTickLen)); return; }
    if (name == "ImPlotStyleVar_MinorTickLen") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotStyleVar_MinorTickLen)); return; }
    if (name == "ImPlotStyleVar_MajorTickSize") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotStyleVar_MajorTickSize)); return; }
    if (name == "ImPlotStyleVar_MinorTickSize") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotStyleVar_MinorTickSize)); return; }
    if (name == "ImPlotStyleVar_MajorGridSize") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotStyleVar_MajorGridSize)); return; }
    if (name == "ImPlotStyleVar_MinorGridSize") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotStyleVar_MinorGridSize)); return; }
    if (name == "ImPlotStyleVar_PlotPadding") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotStyleVar_PlotPadding)); return; }
    if (name == "ImPlotStyleVar_LabelPadding") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotStyleVar_LabelPadding)); return; }
    if (name == "ImPlotStyleVar_LegendPadding") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotStyleVar_LegendPadding)); return; }
    if (name == "ImPlotStyleVar_LegendInnerPadding") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotStyleVar_LegendInnerPadding)); return; }
    if (name == "ImPlotStyleVar_LegendSpacing") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotStyleVar_LegendSpacing)); return; }
    if (name == "ImPlotStyleVar_MousePosPadding") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotStyleVar_MousePosPadding)); return; }
    if (name == "ImPlotStyleVar_AnnotationPadding") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotStyleVar_AnnotationPadding)); return; }
    if (name == "ImPlotStyleVar_FitPadding") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotStyleVar_FitPadding)); return; }
    if (name == "ImPlotStyleVar_PlotDefaultSize") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotStyleVar_PlotDefaultSize)); return; }
    if (name == "ImPlotStyleVar_PlotMinSize") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotStyleVar_PlotMinSize)); return; }
    if (name == "ImPlotStyleVar_COUNT") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotStyleVar_COUNT)); return; }
    if (name == "ImPlotScale_Linear") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotScale_Linear)); return; }
    if (name == "ImPlotScale_Time") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotScale_Time)); return; }
    if (name == "ImPlotScale_Log10") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotScale_Log10)); return; }
    if (name == "ImPlotScale_SymLog") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotScale_SymLog)); return; }
    if (name == "ImPlotMarker_None") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotMarker_None)); return; }
    if (name == "ImPlotMarker_Circle") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotMarker_Circle)); return; }
    if (name == "ImPlotMarker_Square") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotMarker_Square)); return; }
    if (name == "ImPlotMarker_Diamond") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotMarker_Diamond)); return; }
    if (name == "ImPlotMarker_Up") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotMarker_Up)); return; }
    if (name == "ImPlotMarker_Down") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotMarker_Down)); return; }
    if (name == "ImPlotMarker_Left") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotMarker_Left)); return; }
    if (name == "ImPlotMarker_Right") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotMarker_Right)); return; }
    if (name == "ImPlotMarker_Cross") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotMarker_Cross)); return; }
    if (name == "ImPlotMarker_Plus") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotMarker_Plus)); return; }
    if (name == "ImPlotMarker_Asterisk") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotMarker_Asterisk)); return; }
    if (name == "ImPlotMarker_COUNT") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotMarker_COUNT)); return; }
    if (name == "ImPlotColormap_Deep") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotColormap_Deep)); return; }
    if (name == "ImPlotColormap_Dark") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotColormap_Dark)); return; }
    if (name == "ImPlotColormap_Pastel") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotColormap_Pastel)); return; }
    if (name == "ImPlotColormap_Paired") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotColormap_Paired)); return; }
    if (name == "ImPlotColormap_Viridis") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotColormap_Viridis)); return; }
    if (name == "ImPlotColormap_Plasma") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotColormap_Plasma)); return; }
    if (name == "ImPlotColormap_Hot") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotColormap_Hot)); return; }
    if (name == "ImPlotColormap_Cool") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotColormap_Cool)); return; }
    if (name == "ImPlotColormap_Pink") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotColormap_Pink)); return; }
    if (name == "ImPlotColormap_Jet") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotColormap_Jet)); return; }
    if (name == "ImPlotColormap_Twilight") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotColormap_Twilight)); return; }
    if (name == "ImPlotColormap_RdBu") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotColormap_RdBu)); return; }
    if (name == "ImPlotColormap_BrBG") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotColormap_BrBG)); return; }
    if (name == "ImPlotColormap_PiYG") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotColormap_PiYG)); return; }
    if (name == "ImPlotColormap_Spectral") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotColormap_Spectral)); return; }
    if (name == "ImPlotColormap_Greys") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotColormap_Greys)); return; }
    if (name == "ImPlotLocation_Center") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotLocation_Center)); return; }
    if (name == "ImPlotLocation_North") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotLocation_North)); return; }
    if (name == "ImPlotLocation_South") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotLocation_South)); return; }
    if (name == "ImPlotLocation_West") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotLocation_West)); return; }
    if (name == "ImPlotLocation_East") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotLocation_East)); return; }
    if (name == "ImPlotLocation_NorthWest") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotLocation_NorthWest)); return; }
    if (name == "ImPlotLocation_NorthEast") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotLocation_NorthEast)); return; }
    if (name == "ImPlotLocation_SouthWest") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotLocation_SouthWest)); return; }
    if (name == "ImPlotLocation_SouthEast") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotLocation_SouthEast)); return; }
    if (name == "ImPlotBin_Sqrt") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotBin_Sqrt)); return; }
    if (name == "ImPlotBin_Sturges") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotBin_Sturges)); return; }
    if (name == "ImPlotBin_Rice") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotBin_Rice)); return; }
    if (name == "ImPlotBin_Scott") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotBin_Scott)); return; }
    if (name == "ImPlotFlags_YAxis2") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotFlags_YAxis2)); return; }
    if (name == "ImPlotFlags_YAxis3") { getOutput(outputs, 0) = createScalarDouble(factory, static_cast<double>(ImPlotFlags_YAxis3)); return; }
    throwError(matlabPtr, "Unknown {lib} constant: " + name);
  });
}

} // namespace ps_mex
